### ISSUE TITLE
Table component onRowClick issue

### ISSUE THREAD

**Issue by Santosh8055** [resin-io-modules/rendition#534] opened 2018-07-27 13:57 UTC
**Describe the bug**
After sorting a row in the Table component, onRowClick's first parameter is wrong in the callback

**To Reproduce**
1) import Table from the rendition with all sortable fields

2) add onRowClick the table

3) Sort any column and click on the row

4) Click on the row (I guess this goes without saying ;)

**Expected behavior**
the first parameter of the call back should return the proper row, but it is returning according to the original index.

**Comment by thgreasi** [comment] 2018-07-27 14:11
Just tried that [in the story book](https://resin-io-modules.github.io/rendition/?selectedKind=Core%2FTable&selectedStory=Row%20Click&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) and can't reproduce!?

![peek 2018-07-27 17-08](https://user-images.githubusercontent.com/1295829/43325762-16071118-91c0-11e8-80d0-8dd8bef05d14.gif)

Can you post some additional details on how to reproduce (a fiddle or even a gif is welcome as well).

**Comment by Santosh8055** [comment] 2018-07-27 14:17
Hi,

Sorry, I'll set up a fiddle as soon as possible and update you. Thanks for the quick response

**Comment by rsiwady29** [comment] 2018-08-02 05:09
I'm also seeing the same behavior. Wasn't able to setup a fiddle for easier reproduction but here's a small repo I put together: https://github.com/rsiwady29/rendition-table-issue

**Comment by thgreasi** [comment] 2018-08-02 06:29
@rsiwady29 adding the `rowKey="name"` to the table of your repo fixes the issue.
I see that while the docs state that the `rowKey` prop is required for the `onCheck` to work, it isn't for the `onRowClick`.
Opened #541 to track updating the docs.
Closing for now, give us a note if you still face an issue.

**Closed by thgreasi** 2018-08-02 06:29 UTC
Labels: needs more info
